import {
  Anchor,
  Award,
  BadgeCheck,
  BarChart,
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle,
  Clock,
  Computer,
  Database,
  FileCheck,
  FileText,
  Globe,
  Headset,
  HeartHandshake,
  MapPin,
  MessageSquare,
  Network,
  Package,
  Shield,
  Ship,
  Smile,
  Star,
  Thermometer,
  ThumbsUp,
  TrendingUp,
  Truck,
  Users,
  type LucideIcon,
} from "lucide-react";

const registry: Record<string, LucideIcon> = {
  Anchor,
  Award,
  BadgeCheck,
  BarChart,
  BarChart3,
  Briefcase,
  Building2,
  Calendar,
  CheckCircle,
  Clock,
  Computer,
  Database,
  FileCheck,
  FileText,
  Globe,
  Headset,
  HeartHandshake,
  MapPin,
  MessageSquare,
  Network,
  Package,
  Shield,
  Ship,
  Smile,
  Star,
  Thermometer,
  ThumbsUp,
  TrendingUp,
  Truck,
  Users,
};

/** Resolves an icon name stored in the database to a lucide-react component. */
export function getIcon(name: string): LucideIcon {
  return registry[name] ?? Shield;
}

/** Names editors can pick from when adding/editing an icon field. */
export const iconNames = Object.keys(registry);
